=== Inserting elements adjacent to an existing DOM element

==== Problem

You want to insert an element before or after another element.

==== Solution

Use an element's `insertAdjacentElement()` method to insert another element
immediately before or immediately after it. Or, use the `insertBefore()` method.
Examples of both are shown below.
 
==== Examples

Consider this HTML file. You want to insert two new <li> elements into the <ul>,
one before the <li> with the 'target' ID, and one after it:

--------------------------------------------------------------------------------
<!DOCTYPE html>

<html>
  <body>   
    <ul>
      <li>First item</li>
      <li id='target'>Target item</li>
      <li>Last item</li>
    </ul>
    
    <script type='application/dart' src='main.dart'></script>
    
    <script src="packages/browser/dart.js"></script>
  </body>
</html>
--------------------------------------------------------------------------------

In the accompanying Dart file, get a reference to the target <li>.  Then,
invoke the `insertAdjacentElement()` method on that <li> to insert new elements next to it:

--------------------------------------------------------------------------------
import 'dart:html';

void main() {
  var targetItem = query('#target');

  var li = new LIElement();
  li.text = 'Added before target';
  targetItem.insertAdjacentElement('beforeBegin', li);
  
  li = new LIElement();
  li.text = 'Added after target';
  targetItem.insertAdjacentElement('afterEnd', li);
}

--------------------------------------------------------------------------------


The first argument to `insertAdjacentElement()` indicates where the new
element is inserted, with 'beforeBegin' inserting it before the target element

The first argument to `insertAdjacentElement()` indicates where the new
element is inserted. If it is 'beforeBegin', the new element is inserted
immediately before the target element. If it is 'afterEnd', the new element is
inserted immediately after the target element.

The list looks like this after the new elements have been inserted:

--------------------------------------------------------------------------------
First item
Added before target
Target item
Added after target
Last item
--------------------------------------------------------------------------------

You can also use the `insertBefore()` method to insert an element into the
DOM. Call `insertBefore()` on the target element's parent node:

--------------------------------------------------------------------------------
import 'dart:html';
      
void main() {
  var targetItem = query('#target');

  var li = new LIElement();
  li.text = 'Added before target';
  targetItem.parent.insertBefore(li, targetItem);
  
  li = new LIElement();
  li.text = 'Added after target';
  // Insert after the target element.
  targetItem.parent.insertBefore(li, targetItem.nextElementSibling);
}
--------------------------------------------------------------------------------


