= Dart Cookbook
:author: Shailen Tuli
:encoding: UTF-8

== Numbers

=== Converting a string to a number

==== Problem

You want to parse a string and convert it to a number.


==== Solution

Use `int.parse` to convert a string to an int:

--------------------------------------------------------------------------------
print(int.parse('231')); // 231
--------------------------------------------------------------------------------

The strings can be prefixed with a '+' or a '-':

--------------------------------------------------------------------------------
print(int.parse('+231')); // 231
print(int.parse('-231')); // -231
--------------------------------------------------------------------------------
    
You can pass in the radix as a second argument:

--------------------------------------------------------------------------------
print(int.parse('231', radix: 16));  // 561
print(int.parse('F34A', radix: 16)); // 62282
--------------------------------------------------------------------------------
    
Strings starting with '0x', '-0x' or '+0x' are assumed to have a radix of 16:

--------------------------------------------------------------------------------
print(int.parse('0x231')); // 561
--------------------------------------------------------------------------------

Use `double.parse` to convert a string to a double:

--------------------------------------------------------------------------------
print(double.parse('3.14')); // 3.14
--------------------------------------------------------------------------------
    
The method accepts exponential notation:

--------------------------------------------------------------------------------
print(double.parse('3.14e5')); // 314000.0
--------------------------------------------------------------------------------

Both `int.parse` and `double.parse` throw a FormatException if they are passed
invalid arguments.


=== Converting a number to a string

==== Problem

You want to convert a number to a string.

==== Solution

Use `toString()` to convert a number to a string:

--------------------------------------------------------------------------------
1234.toString();   // '1234'
3.1519.toString(); // '3.1519'
--------------------------------------------------------------------------------

To specify the number of signficant digits, use the `toStringAsPrecision()`
method: 

--------------------------------------------------------------------------------
1234.toStringAsPrecision(5);   // '1234.0'
3.1519.toStringAsPrecision(8); // '3.1519000'
--------------------------------------------------------------------------------
  
To specify the number of digits after the decimal, use `toStringAsFixed()`:

--------------------------------------------------------------------------------
1234.toStringAsFixed(2);   // '1234.00'
3.1519.toStringAsFixed(2); // '3.15'
--------------------------------------------------------------------------------

To convert the number to decimal exponential notation, use the
`toStringAsExponential()` method: 

--------------------------------------------------------------------------------
1234.toStringAsExponential();   // '1.234e+3'
--------------------------------------------------------------------------------



 


