=== Removing an element from the DOM

====  Problem

You want to remove an element from the DOM.

==== Solution

Call the `remove()` method on an element. Doing so removes the element
from the DOM.

==== Example

The following example shows a list of items, some of which are out of stock.
If the user decides that she does not want to see the out of stock items, she
can click on a link that triggers a callback that remove those items from the
DOM: 

--------------------------------------------------------------------------------
<!DOCTYPE html>
<head>
  <style>
    .out-of-stock {color: #aaa};  
  </style>  
</head>
<html>
  <body>
    <ul>
      <li>Selection:
       <ul>
          <li>Toyota
            <ul>
              <li>Prius</li>
              <li class='out-of-stock'>Camry Hybrid</li>
              <li>Rav 4</li>
            </ul>
          </li>
          
          <li>Honda
            <ul>
              <li class='out-of-stock'>Civic</li>
              <li>Accord</li>
            </ul>
          </li>
          
          <li>Nissan
            <ul>
              <li>Altima</li>
              <li class='out-of-stock'>Pathfinder</li>
            </ul>
          </li>
        </ul>
      </li>
    </ul>
  
    <p><a href='#'>Show only in-stock</a></p>
   
    <script type="application/dart">
      
      import 'dart:html';
      
      void main() {
        
        query('a').onClick.listen((event) {
        
          // Remove all out of stock items from the DOM.
          queryAll('.out-of-stock').forEach((item) {
            item.remove();
          });
          
          event.preventDefault();
          event.target.remove();
        });
      }
      
    </script>
    <script src="packages/browser/dart.js"></script>
  </body>
</html>
--------------------------------------------------------------------------------


==== Discussion

Using `remove()` works well if you have a reference to the DOM element you
want to remove. But sometimes, you only have a reference to the element's
parent.  For example, you may want to remove an <li> that you don't have a
direct reference to. If you have a reference to the <ul> or <ol> that
contains the <li>, you can use list methods to remove the <li> from the list
of its parent's children. Doing so removes the <li> from the DOM.

You can obtain a list of an element's children through its `children`
property:

--------------------------------------------------------------------------------
List<Element> children = query('ol').children;
--------------------------------------------------------------------------------

Use `removeAt()` to remove an element by its index position:

--------------------------------------------------------------------------------
element.children.removeAt(1);
--------------------------------------------------------------------------------

Remove the last child element using `removeLast()`: 

--------------------------------------------------------------------------------
element.children.removeLast();
--------------------------------------------------------------------------------

You can query the collection of children and remove a matching element using
`remove()`:

--------------------------------------------------------------------------------
element.children.remove(element.query('.largest'));
--------------------------------------------------------------------------------

You can remove all child elements using the `clear()` method:

--------------------------------------------------------------------------------
element.children.clear();
--------------------------------------------------------------------------------



