/// Use the Link `target()` method to get the path that the link points to.

import 'dart:async';
import 'dart:io';

// Creates temporary directory inside the system temp directory, creates a
// couple of paths in the created directory, and creates a symlink.
Future<Link> createSymlink() {
  return Directory.systemTemp.createTemp('my_temp_dir').then((temp) {
    var first = '${temp.path}${Platform.pathSeparator}first';
    var second = '${temp.path}${Platform.pathSeparator}second';
    return new Link(second).create(first);
  });
}

void main() {
  createSymlink()
    .then((Link link) {
      print(link.path); // Prints path that ends with 'second'.
      link.target().then((String targetPath) {
        // Do something with the targetPath that ends with 'first'.
      })
      // Catch any error generated by link.target().
      .catchError((e) {
        print(e.message);
      });
    });
}